name: sdl3-cases
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyterlab
  - ipywidgets
  - numpy
  - matplotlib
  - folium
  - rasterio
  - geopandas
  - contextily
  - pip
  - pip:
      - openeo
      - git+https://github.com/TobiasEdman/imintengine.git
