apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: training-data
  namespace: prithvi-training-default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
